package com.fintrack.backend.analysis.service;

import com.fintrack.backend.analysis.dto.FinancialReportDTO;
import org.springframework.stereotype.Service;

import java.util.StringJoiner;

@Service
public class ExportService {

    public byte[] exportToPdf(FinancialReportDTO report) {
        try {
            String pdfContent = generateSimplePdfContent(report);
            return pdfContent.getBytes();
        } catch (Exception e) {
            throw new RuntimeException("PDF export failed", e);
        }
    }

    public byte[] exportToCsv(FinancialReportDTO report) {
        StringJoiner csv = new StringJoiner("\n");
        csv.add("Category,Amount");

        if (report.getCategorySummary() != null) {
            report.getCategorySummary().forEach((category, amount) -> {
                csv.add(category + "," + amount);
            });
        }

        csv.add("Total Income," + report.getTotalIncome());
        csv.add("Total Expense," + report.getTotalExpense());
        csv.add("Balance," + report.getBalance());

        return csv.toString().getBytes();
    }

    private String generateSimplePdfContent(FinancialReportDTO report) {
        StringBuilder pdfContent = new StringBuilder();
        pdfContent.append("=== BÁO CÁO TÀI CHÍNH ===\n\n");
        pdfContent.append("Thời gian: Tháng ").append(report.getMonth()).append("/").append(report.getYear()).append("\n\n");
        pdfContent.append("TỔNG QUAN:\n");
        pdfContent.append("- Thu nhập: ").append(String.format("%,.0f", report.getTotalIncome())).append(" VND\n");
        pdfContent.append("- Chi tiêu: ").append(String.format("%,.0f", report.getTotalExpense())).append(" VND\n");
        pdfContent.append("- Số dư: ").append(String.format("%,.0f", report.getBalance())).append(" VND\n\n");

        pdfContent.append("CHI TIẾT CHI TIÊU THEO DANH MỤC:\n");
        if (report.getCategorySummary() != null && !report.getCategorySummary().isEmpty()) {
            report.getCategorySummary().forEach((category, amount) -> {
                double percentage = (amount / report.getTotalExpense()) * 100;
                pdfContent.append("- ").append(category).append(": ")
                        .append(String.format("%,.0f", amount)).append(" VND (")
                        .append(String.format("%.1f", percentage)).append("%)\n");
            });
        } else {
            pdfContent.append("- Không có dữ liệu chi tiêu\n");
        }

        pdfContent.append("\n---\n");
        pdfContent.append("Generated by FinTrack System");

        return pdfContent.toString();
    }
}