services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      timeout: 10s
      retries: 10
      interval: 5s
    networks:
      - minilab

  backend:
    build: ./backend
    image: ${DOCKER_REGISTRY}/vissmart-backend:${TAG:-latest}
    container_name: backend
    ports: ["8080:8080"]
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - HOST=mysql
      - PORT=3306
      - DATABASE=${MYSQL_DATABASE}
      - USERNAME=${MYSQL_USER}
      - PASSWORD=${MYSQL_PASSWORD}
    networks:
      - minilab

  frontend:
    build: ./frontend
    image: ${DOCKER_REGISTRY}/vissmart-frontend:${TAG:-latest}
    container_name: frontend
    ports: ["81:80"]
    environment:
      - BACKEND_HOST=${BACKEND_HOST:-backend}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
    networks:
      - minilab

volumes:
  mysql-data:

networks:
  minilab:
    driver: bridge